<?$APPLICATION->IncludeComponent(
		"bitrix:catalog.comments", 
		".default", 
		array(
			"CACHE_TIME" => "0",
			"CACHE_TYPE" => "A",
			"COMMENTS_COUNT" => "5",
			"ELEMENT_CODE" => "",
			"ELEMENT_ID" => $arElement["ID"],
			"FB_USE" => "Y",
			"IBLOCK_ID" => $arParams["IBLOCK_ID"],
			"IBLOCK_TYPE" => "aspro_digital_catalog",
			"SHOW_DEACTIVATED" => "N",
			"TEMPLATE_THEME" => "blue",
			"URL_TO_COMMENT" => "",
			"VK_USE" => "Y",
			"AJAX_POST" => "Y",
			"WIDTH" => "",
			"COMPONENT_TEMPLATE" => ".default",
			"BLOG_USE" => "Y",
			"BLOG_TITLE" => "Комментарии",
			"BLOG_URL" => "catalog_comments",
			"PATH_TO_SMILE" => "/bitrix/images/blog/smile/",
			"EMAIL_NOTIFY" => "Y",
			"SHOW_SPAM" => "Y",
			"SHOW_RATING" => "Y",
			"RATING_TYPE" => "like_graphic",
			"FB_TITLE" => "Facebook",
			"FB_USER_ADMIN_ID" => "",
			"FB_APP_ID" => "",
			"FB_COLORSCHEME" => "light",
			"FB_ORDER_BY" => "social",
			"VK_TITLE" => "Вконтакте",
			"VK_API_ID" => "5892969"
		),
		false
	);?>